# AWS S3 설정 (운영 환경 전용)
spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}
      cloudfront:
        domain: ${AWS_DOMAIN}
        distribution-id: ${AWS_DISTRIBUTION_ID}
