spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

    application:
        name: sealog-backend

    data:
        rest:
            base-path: /api

    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB

server:
    port: ${SERVER_PORT:8080}

sealog:
    storage:
        type: ${STORAGE_TYPE:local}

logging:
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 30

springdoc:
  swagger-ui:
    path: /docs
