name: sealog-dev

services:
  mariadb-dev:
    image: mariadb:11.4.8
    container_name: sealog-mariadb-dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: devdb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpass
    volumes:
      - mariadb_data_dev:/var/lib/mysql

  redis-dev:
    image: redis:7.2-alpine
    container_name: sealog-redis-dev
    restart: always
    ports:
      - "6379:6379"

volumes:
  mariadb_data_dev: